### ISSUE TITLE
How to use res50 model retrain res50-ibna?

### ISSUE THREAD

**Issue by KaiHoo** [XingangPan/IBN-Net#11]
**### There are instance norm  in IBN models, how to use res50 model retrain res50-ibna?**

File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNet:
	Missing key(s) in state_dict: "layer1.0.bn1.IN.weight", "layer1.0.bn1.IN.bias", "layer1.0.bn1.BN.weight", "layer1.0.bn1.BN.bias", "layer1.0.bn1.BN.running_mean", "layer1.0.bn1.BN.running_var", "layer1.1.bn1.IN.weight", "layer1.1.bn1.IN.bias", "layer1.1.bn1.BN.weight", "layer1.1.bn1.BN.bias", "layer1.1.bn1.BN.running_mean", "layer1.1.bn1.BN.running_var", "layer1.2.bn1.IN.weight", "layer1.2.bn1.IN.bias", "layer1.2.bn1.BN.weight", "layer1.2.bn1.BN.bias", "layer1.2.bn1.BN.running_mean", "layer1.2.bn1.BN.running_var", "layer2.0.bn1.IN.weight", "layer2.0.bn1.IN.bias", "layer2.0.bn1.BN.weight", "layer2.0.bn1.BN.bias", "layer2.0.bn1.BN.running_mean", "layer2.0.bn1.BN.running_var", "layer2.1.bn1.IN.weight", "layer2.1.bn1.IN.bias", "layer2.1.bn1.BN.weight", "layer2.1.bn1.BN.bias", "layer2.1.bn1.BN.running_mean", "layer2.1.bn1.BN.running_var", "layer2.2.bn1.IN.weight", "layer2.2.bn1.IN.bias", "layer2.2.bn1.BN.weight", "layer2.2.bn1.BN.bias", "layer2.2.bn1.BN.running_mean", "layer2.2.bn1.BN.running_var", "layer2.3.bn1.IN.weight", "layer2.3.bn1.IN.bias", "layer2.3.bn1.BN.weight", "layer2.3.bn1.BN.bias", "layer2.3.bn1.BN.running_mean", "layer2.3.bn1.BN.running_var", "layer3.0.bn1.IN.weight", "layer3.0.bn1.IN.bias", "layer3.0.bn1.BN.weight", "layer3.0.bn1.BN.bias", "layer3.0.bn1.BN.running_mean", "layer3.0.bn1.BN.running_var", "layer3.1.bn1.IN.weight", "layer3.1.bn1.IN.bias", "layer3.1.bn1.BN.weight", "layer3.1.bn1.BN.bias", "layer3.1.bn1.BN.running_mean", "layer3.1.bn1.BN.running_var", "layer3.2.bn1.IN.weight", "layer3.2.bn1.IN.bias", "layer3.2.bn1.BN.weight", "layer3.2.bn1.BN.bias", "layer3.2.bn1.BN.running_mean", "layer3.2.bn1.BN.running_var", "layer3.3.bn1.IN.weight", "layer3.3.bn1.IN.bias", "layer3.3.bn1.BN.weight", "layer3.3.bn1.BN.bias", "layer3.3.bn1.BN.running_mean", "layer3.3.bn1.BN.running_var", "layer3.4.bn1.IN.weight", "layer3.4.bn1.IN.bias", "layer3.4.bn1.BN.weight", "layer3.4.bn1.BN.bias", "layer3.4.bn1.BN.running_mean", "layer3.4.bn1.BN.running_var", "layer3.5.bn1.IN.weight", "layer3.5.bn1.IN.bias", "layer3.5.bn1.BN.weight", "layer3.5.bn1.BN.bias", "layer3.5.bn1.BN.running_mean", "layer3.5.bn1.BN.running_var".
	Unexpected key(s) in state_dict: "layer1.0.bn1.running_mean", "layer1.0.bn1.running_var", "layer1.0.bn1.weight", "layer1.0.bn1.bias", "layer1.1.bn1.running_mean", "layer1.1.bn1.running_var", "layer1.1.bn1.weight", "layer1.1.bn1.bias", "layer1.2.bn1.running_mean", "layer1.2.bn1.running_var", "layer1.2.bn1.weight", "layer1.2.bn1.bias", "layer2.0.bn1.running_mean", "layer2.0.bn1.running_var", "layer2.0.bn1.weight", "layer2.0.bn1.bias", "layer2.1.bn1.running_mean", "layer2.1.bn1.running_var", "layer2.1.bn1.weight", "layer2.1.bn1.bias", "layer2.2.bn1.running_mean", "layer2.2.bn1.running_var", "layer2.2.bn1.weight", "layer2.2.bn1.bias", "layer2.3.bn1.running_mean", "layer2.3.bn1.running_var", "layer2.3.bn1.weight", "layer2.3.bn1.bias", "layer3.0.bn1.running_mean", "layer3.0.bn1.running_var", "layer3.0.bn1.weight", "layer3.0.bn1.bias", "layer3.1.bn1.running_mean", "layer3.1.bn1.running_var", "layer3.1.bn1.weight", "layer3.1.bn1.bias", "layer3.2.bn1.running_mean", "layer3.2.bn1.running_var", "layer3.2.bn1.weight", "layer3.2.bn1.bias", "layer3.3.bn1.running_mean", "layer3.3.bn1.running_var", "layer3.3.bn1.weight", "layer3.3.bn1.bias", "layer3.4.bn1.running_mean", "layer3.4.bn1.running_var", "layer3.4.bn1.weight", "layer3.4.bn1.bias", "layer3.5.bn1.running_mean", "layer3.5.bn1.running_var", "layer3.5.bn1.weight", "layer3.5.bn1.bias".

**Comment by XingangPan** [comment]
You cannot use res50 model to retrain res50-ibna. If you want to use pretrained res50-ibna, you should use the same architecture, i.e., res50-ibna, too.
