### ISSUE TITLE
Segmentation implementation

### ISSUE THREAD

**Issue by erichhhhho** [XingangPan/IBN-Net#14]
Hi, Nice work!

I have a question, Would you mind sharing what decoder or upsampling method you are using in semantic segmentation, after setting the IBN nets as the backbone?  

Or could you share more about the implementation details on this? (finetuning in cityscapes and cross domain Experiments) As you didn't mention much in the paper

**Comment by XingangPan** [comment]
For semantic segmentation, our pipeline is similar to PSPNet without Pyramid Pooling Module.
There is no decoder, the output of the backbone is upsampled by 8 times using bilinear interpolation.
Our code is modified from this repo https://github.com/meetshah1995/pytorch-semseg

**Comment by erichhhhho** [comment]
Thx!

**Comment by EmmaW8** [comment]
@erichhhhho 
Hi, have you reproduced the segmentation part?
I am also interested in this segmentation implementation.
@XingangPan 
Thanks for the released wonderful work. Will the segmentation models be released in the future?
