### ISSUE TITLE
can't archive weights from the tar file

### ISSUE THREAD

**Issue by absorbguo** [XingangPan/IBN-Net#17]
folllowing the download link, I can't archive the tar files. Does anybody come across this problem?

**Comment by absorbguo** [comment]
Download link:https://drive.google.com/drive/folders/1JxSo6unmvwkCavEqh42NDKYUG29HoLE0

**Comment by XingangPan** [comment]
@absorbguo You do not need to archive the tar files, as they are actually .pth files. You can load it directly using pytorch. I'll modify the name of these files later.

**Comment by absorbguo** [comment]
> @absorbguo You do not need to archive the tar files, as they are actually .pth files. You can load it directly using pytorch. I'll modify the name of these files later.

It works，Thank you for your prompt reply
