### ISSUE TITLE
Syntax Error: 'async' is now a reserved word in Python 3.7

### ISSUE THREAD

**Issue by cclauss** [XingangPan/IBN-Net#2]
flake8 testing of https://github.com/XingangPan/IBN-Net on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./imagenet.py:250:63: E999 SyntaxError: invalid syntax
            inputs, targets = inputs.cuda(), targets.cuda(async=True)
                                                              ^
1     E999 SyntaxError: invalid syntax
1
```

**Comment by XingangPan** [comment]
I guess you are using pytorch0.4.0 or later version. I'll add a new branch for this issue.

**Comment by XingangPan** [comment]
A new branch is added for pytorch0.4.1.
