### ISSUE TITLE
应该把哪些BN层替换为IBN

### ISSUE THREAD

**Issue by splinter21** [XingangPan/IBN-Net#22]
论文里是bottleneck的第一个1x1后的BN层，然而bottleneck里有3个BN层，可选择性非常多。只能通过实验确定替换哪些是合适的选择，还是可以有理论依据？
论文中只做了第一个(a)，和第一个+第二个(ax2)的实验，有没有做其他的替换组合？

**Comment by XingangPan** [comment]
1. bottleneck里3个BN层，加在前两个位置结果差不多，在第三个位置可能会破坏与identity path的alignment.
2. 关于比较复杂的组合的详细讨论不是本文的重点，本文主要是提供了IBN-a/b这两种较为简洁的方案，基于两个规则：1）适量引入IN保留大部分BN， 2）不在网络深层使用IN
