### ISSUE TITLE
Do you have the pytorch 1.0 version's pretrained model?

### ISSUE THREAD

**Issue by clw5180** [XingangPan/IBN-Net#23]
RT, thanks !

**Comment by XingangPan** [comment]
@clw5180 I think the 0.4.1 version's pretrained model is compatible with pytorch1.0. Please let me know if any error occurs.

**Comment by clw5180** [comment]
> @clw5180 I think the 0.4.1 version's pretrained model is compatible with pytorch1.0. Please let me know if any error occurs.

Yes, it's almost compatible with pytorch1.1 . I just use these code to load:
`        
        param_dict = torch.load(model_path)
        param_dict = param_dict['ict']   # don't know why there is a key 'ict'
`
By the way, is resnext pretrained model 32x4d ?

**Comment by XingangPan** [comment]
Yes, it's 32x4d.
