### ISSUE TITLE
can you provide resnet50_ibn_a pre_model?

### ISSUE THREAD

**Issue by H-YunHui** [XingangPan/IBN-Net#24]

**Comment by XingangPan** [comment]
The link of the pre-trained models are provided in the table in README.
The link of resnet50_ibn_a pre_model is https://github.com/XingangPan/IBN-Net/releases/download/v1.0/resnet50_ibn_a-d9d0bb7b.pth

**Comment by H-YunHui** [comment]
@XingangPan 
In the paper, you use IN+BN in residuals 2 through 4, but I want to use it in residuals 2, some of the errors are as follows:
“KeyError: 'layer2.0.bn1.IN.weight”

**Comment by XingangPan** [comment]
@H-YunHui You cannot use the pretrained model weight after changing the model. Alternatively, you may rename the layer that you changed to avoid confilict, and load the model with `strict=False`.
