### ISSUE TITLE
Request more variants such as ResNet-18

### ISSUE THREAD

**Issue by RSKothari** [XingangPan/IBN-Net#25]
Hello,

Would it be possible for you to add more variants to mimic the ResNet architecture provided by pytorch? This enables us to perform principled comparisons on different levels of complexity. Excited to follow your work.

**Comment by XingangPan** [comment]
Thanks for your interests in our work. I'll add ResNet18 and ResNet34 recently.

**Comment by XingangPan** [comment]
@RSKothari IBN-Net variants based on ResNet18 and ResNet34 are added now.
