### ISSUE TITLE
Is IBN = MVN_layer in caffe？

### ISSUE THREAD

**Issue by mathyyj** [XingangPan/IBN-Net#4]
Is IBN layer just "MVN_layer in caffe"？

Thank you very much!

**Comment by XingangPan** [comment]
Instance normalization (IN) layer is "MVN_layer in caffe" plus a scale and shift operation.
IBN layer is half IN half BN.

**Comment by mathyyj** [comment]
I see, so it should be MVN_layer + Scale_layer

many thanks again ~
