### ISSUE TITLE
IBN-Net applied generative model

### ISSUE THREAD

**Issue by XuyangHu** [XingangPan/IBN-Net#5]
Hello! Does IBN-Net can improve generalization on the generative model? Have you ever done any tests on GAN?

**Comment by XingangPan** [comment]
Hi, I haven't done any test on generative model. The purpose of IBN-Net is to improve generalization on high-level vision tasks like image classification or semantic segmentation.
For generative model, you could refer to this paper: https://arxiv.org/pdf/1806.10779.pdf

**Comment by huxuyangahu** [comment]
Thank you for your reply!
