### ISSUE TITLE
下载resnet101_ibn_a.pth.tar之后解压不了，提示数据损坏，能否直接提供.pth文件

### ISSUE THREAD

**Issue by scoobym** [XingangPan/IBN-Net#8]
下载resnet101_ibn_a.pth.tar之后解压不了，提示数据损坏，能否直接提供.pth文件

**Comment by XingangPan** [comment]
@scoobym resnet101_ibn_a.pth.tar不用解压，pytorch可直接读取

**Comment by 2110317008** [comment]
> 下载resnet101_ibn_a.pth.tar之后解压不了，提示数据损坏，能否直接提供.pth文件

打扰了！！请问您是在哪下载的resnet101_ibn_a.pth.tar文件？

**Comment by 2806099072** [comment]
> @scoobym resnet101_ibn_a.pth.tar不用解压，pytorch可直接读取

您好！我现在也需要文件resnet101_ibn_a.pth.tar。您能提供一下吗？
